name: 'dbt_vitao'
version: '0.0.3'

require-dbt-version: [">=1.2.0", "<2.0.0"]

config-version: 2

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
log-path: "logs"

target-path: "target" 
clean-targets:
  - "target"
  - "dbt_packages"

dispatch:
  - macro_namespace: dbt
    search_order: ['dbt_vitao', 'dbt']
